const itemData = {

    ITEM_TYPE_CATEGORY: {
        TYPE_CLOTHING: 0, //clothing item
        TYPE_PROP: 1, //prop item

        TYPE_WEAPON: 2, //weapon item
        TYPE_FOOD: 3, //food item
        TYPE_DRINK: 4, //drink item

        TYPE_MISC: 5 //misc
    },

    ITEM_TYPES: {
        ITEM_TYPE_HAT: "hat",
        ITEM_TYPE_MASK: "mask",
        ITEM_TYPE_GLASSES: "glasses",
        ITEM_TYPE_EARRINGS: "earRings",
        ITEM_TYPE_CHAIN: "chain",
        ITEM_TYPE_TSHIRT: "tShirt",
        ITEM_TYPE_TOP: "top",
        ITEM_TYPE_ARMOUR: "armour",
        ITEM_TYPE_WATCH: "watch",
        ITEM_TYPE_GLOVES: "gloves",
        ITEM_TYPE_PANTS: "pants",
        ITEM_TYPE_SHOES: "shoes",
        ITEM_TYPE_BACKPACK: "backpack",
        ITEM_TYPE_WALLET: "wallet",

        ITEM_TYPE_DAGGER: "weapon_dagger",
        ITEM_TYPE_BAT: "weapon_bat",
        ITEM_TYPE_BOTTLE: "weapon_bottle",
        ITEM_TYPE_CROWBAR: "weapon_crowbar",
        ITEM_TYPE_FLASHLIGHT: "weapon_flashlight",
        ITEM_TYPE_GOLFCLUB: "weapon_golfclub",
        ITEM_TYPE_HAMMER: "weapon_hammer",
        ITEM_TYPE_HATCHET: "weapon_hatchet",
        ITEM_TYPE_KNUCKLEDUSTER: "weapon_knuckleduster",
        ITEM_TYPE_KNIFE: "weapon_knife",
        ITEM_TYPE_MACHETE: "weapon_machete",
        ITEM_TYPE_SWITCHBLADE: "weapon_switchblade",
        ITEM_TYPE_NIGHTSTICK: "weapon_nightstick",
        ITEM_TYPE_WRENCH: "weapon_wrench",
        ITEM_TYPE_BATTLEAXE: "weapon_battleaxe",
        ITEM_TYPE_POOLCUE: "weapon_poolcue",
        ITEM_TYPE_PISTOL: "weapon_pistol",
        ITEM_TYPE_PISTOL_MK2: "weapon_pistol_mk2",
        ITEM_TYPE_COMBATPISTOL: "weapon_combatpistol",
        ITEM_TYPE_APPISTOL: "weapon_appistol",
        ITEM_TYPE_STUNGUN: "weapon_stungun",
        ITEM_TYPE_PISTOL50: "weapon_pistol50",
        ITEM_TYPE_SNSPISTOL: "weapon_snspistol",
        ITEM_TYPE_SNSPISTOL_MK2: "weapon_snspistol_mk2",
        ITEM_TYPE_HEAVYPISTOL: "weapon_heavypistol",
        ITEM_TYPE_VINTAGEPISTOL: "weapon_vintagepistol",
        ITEM_TYPE_FLAREGUN: "weapon_flaregun",
        ITEM_TYPE_MARKSMANPISTOL: "weapon_marksmanpistol",
        ITEM_TYPE_REVOLVER: "weapon_revolver",
        ITEM_TYPE_REVOLVERMK2: "weapon_revolvermk2",
        ITEM_TYPE_DOUBLEACTION: "weapon_doubleaction",
        ITEM_TYPE_RAYPISTOL: "weapon_raypistol",
        ITEM_TYPE_CERAMICPISTOL: "weapon_ceramicpistol",
        ITEM_TYPE_NAVYREVOLVER: "weapon_navyrevolver",
        ITEM_TYPE_GADGETPISTOL: "weapon_gadgetpistol",
        ITEM_TYPE_STUNGUNMP: "weapon_stungunmp",
        ITEM_TYPE_MICROSMG: "weapon_microsmg",
        ITEM_TYPE_SMG: "weapon_smg",
        ITEM_TYPE_SMG_MK2: "weapon_smg_mk2",
        ITEM_TYPE_ASSAULTSMG: "weapon_assaultsmg",
        ITEM_TYPE_COMBATPDW: "weapon_combatpdw",
        ITEM_TYPE_MACHINEPISTOL: "weapon_machinepistol",
        ITEM_TYPE_MINISMG: "weapon_minismg",
        ITEM_TYPE_RAYCARBINE: "weapon_raycarbine",
        ITEM_TYPE_PUMPSHOTGUN: "weapon_pumpshotgun",
        ITEM_TYPE_PUMPSHOTGUN_MK2: "weapon_pumpshotgun_mk2",
        ITEM_TYPE_SAWNOFFSHOTGUN: "weapon_sawnoffshotgun",
        ITEM_TYPE_ASSAULTSHOTGUN: "weapon_assaultshotgun",
        ITEM_TYPE_BULLPUPSHOTGUN: "weapon_bullpupshotgun",
        ITEM_TYPE_MUKSET: "weapon_mukset",
        ITEM_TYPE_HEAVYSHOTGUN: "weapon_heavyshotgun",
        ITEM_TYPE_DBSHOTGUN: "weapon_dbshotgun",
        ITEM_TYPE_AUTOSHOTGUN: "weapon_autoshotgun",
        ITEM_TYPE_COMBATSHOTGUN: "weapon_combatshotgun",
        ITEM_TYPE_ASSAULTRIFLE: "weapon_assaultrifle",
        ITEM_TYPE_ASSAULTRIFLE_MK2: "weapon_assaultrifle_mk2",
        ITEM_TYPE_CARBINERIFLE: "weapon_carbinerifle",
        ITEM_TYPE_CARBINERIFLE_MK2: "weapon_carbinerifle_mk2",
        ITEM_TYPE_ADVANCEDRIFLE: "weapon_advancedrifle",
        ITEM_TYPE_SPECIALCARBINE: "weapon_specialcarbine",
        ITEM_TYPE_SPECIALCARBINE_MK2: "weapon_specialcarbine_mk2",
        ITEM_TYPE_BULLPUPRIFLE: "weapon_bullpuprifle",
        ITEM_TYPE_BULLPUPRIFLE_MK2: "weapon_bullpuprifle_mk2",
        ITEM_TYPE_COMPACTRIFLE: "weapon_compactrifle",
        ITEM_TYPE_MILITARYRIFLE: "weapon_militaryrifle",
        ITEM_TYPE_HEAVYRIFLE: "weapon_heavyrifle",
        ITEM_TYPE_TACTICALRIFLE: "weapon_tacticalrifle",
        ITEM_TYPE_MG: "weapon_mg",
        ITEM_TYPE_COMBATMG: "weapon_combatmg",
        ITEM_TYPE_COMBATMGMK2: "weapon_combatmgmk2",
        ITEM_TYPE_GUSENBERG: "weapon_gusenberg",
        ITEM_TYPE_SNIPERRIFLE: "weapon_sniperrifle",
        ITEM_TYPE_HEAVYSNIPER: "weapon_heavysniper",
        ITEM_TYPE_HEAVYSNIPERMK2: "weapon_heavysnipermk2",
        ITEM_TYPE_MARKSMANRIFLE: "weapon_marksmanrifle",
        ITEM_TYPE_MARKSMANRIFLEMK2: "weapon_marksmanriflemk2",
        ITEM_TYPE_PRECISIONRIFLE: "weapon_precisionrifle",
        ITEM_TYPE_COMPACTLAUNCHER: "weapon_compactlauncher",
        ITEM_TYPE_FIREWORK: "weapon_firework",
        ITEM_TYPE_GRENADELAUNCHERSMOKE: "weapon_grenadelaunchersmoke",
        ITEM_TYPE_GRENADELAUNCHER: "weapon_grenadelauncher",
        ITEM_TYPE_HOMINGLAUNCHER: "weapon_hominglauncher",
        ITEM_TYPE_MINIGUN: "weapon_minigun",
        ITEM_TYPE_RAILGUN: "weapon_railgun",
        ITEM_TYPE_RPG: "weapon_rpg",
        ITEM_TYPE_BALL: "weapon_ball",
        ITEM_TYPE_BZGAS: "weapon_bzgas",
        ITEM_TYPE_SMOKEGRENADE: "weapon_smokegrenade",
        ITEM_TYPE_FLARE: "weapon_flare",
        ITEM_TYPE_GRENADE: "weapon_grenade",
        ITEM_TYPE_MOLOTOV: "weapon_molotov",
        ITEM_TYPE_PROXIMITYMINE: "weapon_proximitymine",
        ITEM_TYPE_PIPEBOMB: "weapon_pipebomb",
        ITEM_TYPE_SNOWBALL: "weapon_snowball",
        ITEM_TYPE_STICKYBOMB: "weapon_stickybomb"
    },
}

const inventoryAssets = {

    WEAPON_GROUP: {
        UNKNOWN: 3566412288,
        MELEE: 2685387236,
        HANDGUNS: 416676503,
        SUBMACHINE: 3337201152,
        SHOTGUN: 860033945,
        ASSAULTRIFLE: 970310034,
        LIGHTMACHINE: 1159398588,
        SNIPER: 3082541095,
        HEAVYWEAPON: 2725924767,
        THROWABLES: 1548507267,
        MISC: 4257178988
    },

    INVENTORY_CLOTHING: {
        TYPE_HAT: 0,
        TYPE_MASK: 1,
        TYPE_GLASSES: 2,
        TYPE_EARRINGS: 3,
        TYPE_CHAIN: 4,
        TYPE_TSHIRT: 5,
        TYPE_JACKET: 6,
        TYPE_BACKPACK: 7,
        TYPE_WALLET: 8,
        TYPE_ARMOUR: 9,
        TYPE_WATCH: 10,
        TYPE_GLOVES: 11,
        TYPE_PANTS: 12,
        TYPE_SHOES: 13
    },
    INVENTORY_EQUIPMENTS: {
        hat: "0",
        mask: "1",
        glasses: "2",
        earRings: "3",
        chain: "4",
        tShirt: "5",
        top: "6",
        backpack: "7",
        wallet: "8",
        armour: "9",
        watch: "10",
        gloves: "11",
        pants: "12",
        shoes: "13"
    },
    AMMO_TYPES: {
        TYPE_PISTOL: "PISTOLAMMO",
        TYPE_50CAL: "REVOLVERAMMO",
        TYPE_SMG: "SMGAMMO",
        TYPE_GUAGE: "SHOTGUNAMMO",
        TYPE_RIFLE: "RIFLEAMMO",
        TYPE_SNIPER: "SNIPERAMMO",
        TYPE_LMG: "LMGAMMO"
    },
    INVENTORY_CATEGORIES: {
        CLOTHES: "clothes",
        POCKETS: "pockets"
    },


    items: {
        [itemData.ITEM_TYPES.ITEM_TYPE_HAT]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HAT,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "hat.svg",
            render: "hat.svg",
            name: "Hat",
            description: "Headgear.",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],
            modelHash: "prop_proxy_hat_01",
            gender: null,
            isPlaced: false
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MASK]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MASK,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "mask.svg",
            render: "mask.svg",
            name: "Mask",
            description: "Completely hides your face.",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "p_orleans_mask_s"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GLASSES]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GLASSES,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "glasses.svg",
            render: "glasses.svg",
            name: "Glasses",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_cs_sol_glasses"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_EARRINGS]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_EARRINGS,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "earRings.svg",
            render: "earRings.svg",
            name: "Earrings",
            description: "",
            count: 1,
            weight: 0.05,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "p_tmom_earrings_s"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_CHAIN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_CHAIN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "chain.svg",
            render: "chain.svg",
            name: "Chain",
            description: "Perfect accessory to flex.",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_TSHIRT]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_TSHIRT,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "tShirt.svg",
            render: "tShirt.svg",
            name: "T-shirt",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_tshirt_01"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_TOP]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_TOP,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "top.svg",
            render: "top.svg",
            name: "Jacket",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_shirt_01"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_ARMOUR]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_ARMOUR,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "armour.svg",
            render: "armour.svg",
            name: "Body armor",
            description: "Provides protection for the upper torso.",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_bodyarmour_03",
            amount: 100
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_WATCH]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_WATCH,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_PROP,
            hash: "",
            key: "",
            quality: -1,
            image: "watch.svg",
            render: "watch.svg",
            name: "Watch",
            description: "Wristwatch.",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GLOVES]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GLOVES,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "gloves.svg",
            render: "gloves.svg",
            name: "Gloves",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "vw_prop_vw_backpack_01a"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PANTS]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PANTS,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "pants.svg",
            render: "pants.svg",
            name: "Pants",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "bkr_prop_duffel_bag_01a"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SHOES]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SHOES,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: -1,
            image: "shoes.svg",
            render: "shoes.svg",
            name: "Shoes",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 10,
            options: ["putOn", "drop", "trade"],

            gender: null,
            isPlaced: false,
            modelHash: "v_res_fa_shoebox4"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BACKPACK]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BACKPACK,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_CLOTHING,
            hash: "",
            key: "",
            quality: 0,
            image: "backpack.svg",
            render: "backpack.svg",
            name: "Backpack",
            description: "Increases inventory capacity.",
            count: 1,
            weight: 5,
            maxStack: 1,
            isPlaced: false,
            options: ["putOn", "drop", "trade"],
            gender: null,
            modelHash: "vw_prop_vw_backpack_01a"
        },

        [itemData.ITEM_TYPES.ITEM_TYPE_DAGGER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_DAGGER,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "dagger.svg",
            render: "dagger.svg",
            name: "dagger",
            description: "",
            count: 1,
            weight: 0.6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_dagger"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BAT]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BAT,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bat.svg",
            render: "bat.svg",
            name: "bat",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_bat"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BOTTLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BOTTLE,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bottle.svg",
            render: "bottle.svg",
            name: "bottle",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_bottle"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_CROWBAR]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_CROWBAR,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "crowbar.svg",
            render: "crowbar.svg",
            name: "crowbar",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_crowbar"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_FLASHLIGHT]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_FLASHLIGHT,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "flashlight.svg",
            render: "flashlight.svg",
            name: "flashlight",
            description: "",
            count: 1,
            weight: 0.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_FLASHLIGHT"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GOLFCLUB]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GOLFCLUB,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "golfclub.svg",
            render: "golfclub.svg",
            name: "golfclub",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_gclub"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HAMMER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HAMMER,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "hammer.svg",
            render: "hammer.svg",
            name: "hammer",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_hammer"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HATCHET]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HATCHET,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "hatchet.svg",
            render: "hatchet.svg",
            name: "hatchet",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_hatchet"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_KNUCKLEDUSTER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_KNUCKLEDUSTER,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "knuckle.svg",
            render: "knuckle.svg",
            name: "knuckle",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_KNUCKLE"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_KNIFE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_KNIFE,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "knife.svg",
            render: "knife.svg",
            name: "knife",
            description: "",
            count: 1,
            weight: 0.6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_knife_01"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MACHETE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MACHETE,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "machete.svg",
            render: "machete.svg",
            name: "machete",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_w_me_machette"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SWITCHBLADE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SWITCHBLADE,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "switchblade.svg",
            render: "switchblade.svg",
            name: "switchblade",
            description: "",
            count: 1,
            weight: 0.3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_SWITCHBLADE"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_NIGHTSTICK]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_NIGHTSTICK,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "nightstick.svg",
            render: "nightstick.svg",
            name: "nightstick",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_me_nightstick"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_WRENCH]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_WRENCH,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "wrench.svg",
            render: "wrench.svg",
            name: "wrench",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_tool_wrench"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BATTLEAXE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BATTLEAXE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "battleaxe.svg",
            render: "battleaxe.svg",
            name: "battleaxe",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_ld_fireaxe"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_POOLCUE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_POOLCUE,

            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "poolcue.svg",
            render: "poolcue.svg",
            name: "poolcue",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_pool_cue"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pistol.svg",
            render: "pistol.svg",
            name: "Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],
            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PISTOL_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PISTOL_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pistolmk2.svg",
            render: "pistolmk2.svg",
            name: "MK2 Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_COMBATPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_COMBATPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatpistol.svg",
            render: "combatpistol.svg",
            name: "Combat Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_combatpistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_APPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_APPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "appistol.svg",
            render: "appistol.svg",
            name: "Pistol AP",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_appistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_STUNGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_STUNGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "stungun.svg",
            render: "stungun.svg",
            name: "Stungun",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_stungun"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PISTOL50]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PISTOL50,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pistol50.svg",
            render: "pistol50.svg",
            name: "Pistol 50",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_pistol50",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SNSPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SNSPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "snspistol.svg",
            render: "snspistol.svg",
            name: "SNS Pistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_sns_pistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SNSPISTOL_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SNSPISTOL_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "snspistolmk2.svg",
            render: "snspistolmk2.svg",
            name: "MK2 SNS Pistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_sns_pistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HEAVYPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HEAVYPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavypistol.svg",
            render: "heavypistol.svg",
            name: "Heavy Pistol",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_heavypistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_VINTAGEPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_VINTAGEPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "vintagepistol.svg",
            render: "vintagepistol.svg",
            name: "Vintage Pistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_vintage_pistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_FLAREGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_FLAREGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "flaregun.svg",
            render: "flaregun.svg",
            name: "Flaregun",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_flaregun",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MARKSMANPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MARKSMANPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanpistol.svg",
            render: "marksmanpistol.svg",
            name: "Marksman Pistol",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_marksmanpistol ",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_REVOLVER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_REVOLVER,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "revolver.svg",
            render: "heavyrevolver.svg",
            name: "revolver",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_revolver",
            ammoType: "REVOLVERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_REVOLVERMK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_REVOLVERMK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "revolvermk2.svg",
            render: "revolvermk2.svg",
            name: "revolvermk2",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_revolver",
            ammoType: "REVOLVERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_DOUBLEACTION]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_DOUBLEACTION,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "doubleaction.svg",
            render: "doubleaction.svg",
            name: "doubleaction",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "REVOLVERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_RAYPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_RAYPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "raypistol.svg",
            render: "raypistol.svg",
            name: "raypistol",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_CERAMICPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_CERAMICPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "ceramicpistol.svg",
            render: "ceramicpistol.svg",
            name: "ceramicpistol",
            description: "",
            count: 1,
            weight: 1.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_NAVYREVOLVER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_NAVYREVOLVER,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "navyrevolver.svg",
            render: "navyrevolver.svg",
            name: "navyrevolver",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_space_pistol",
            ammoType: "REVOLVERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GADGETPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GADGETPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "gadgetpistol.svg",
            render: "gadgetpistol.svg",
            name: "gadgetpistol",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_heavypistol",
            ammoType: "PISTOLAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_STUNGUNMP]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_STUNGUNMP,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "stungun.svg",
            render: "stungun.svg",
            name: "stungun",
            description: "",
            count: 1,
            weight: 1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_pi_stungun"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MICROSMG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MICROSMG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "microsmg.svg",
            render: "microsmg.svg",
            name: "microsmg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_microsmg",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SMG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SMG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "smg.svg",
            render: "smg.svg",
            name: "smg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_smg",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SMG_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SMG_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "smgmk2.svg",
            render: "smgmk2.svg",
            name: "smgmk2",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_smg",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTSMG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTSMG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultsmg.svg",
            render: "assaultsmg.svg",
            name: "assaultsmg",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_assaultsmg",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_COMBATPDW]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_COMBATPDW,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatpdw.svg",
            render: "combatpdw.svg",
            name: "combatpdw",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_COMBATPDW",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MACHINEPISTOL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MACHINEPISTOL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "machinepistol.svg",
            render: "machinepistol.svg",
            name: "machinepistol",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_MACHINEPISTOL",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MINISMG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MINISMG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "minismg.svg",
            render: "minismg.svg",
            name: "minismg",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "WEAPON_MINISMG",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_RAYCARBINE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_RAYCARBINE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "raycarbine.svg",
            render: "raycarbine.svg",
            name: "raycarbine",
            description: "",
            count: 1,
            weight: 2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "SMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pumpshotgun.svg",
            render: "pumpshotgun.svg",
            name: "pumpshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_pumpshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PUMPSHOTGUN_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pumpshotgunmk2.svg",
            render: "pumpshotgunmk2.svg",
            name: "pumpshotgunmk2",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_pumpshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SAWNOFFSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SAWNOFFSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "sawnoffshotgun.svg",
            render: "sawnoffshotgun.svg",
            name: "sawnoffshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_sawnoff",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultshotgun.svg",
            render: "assaultshotgun.svg",
            name: "assaultshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BULLPUPSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BULLPUPSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpupshotgun.svg",
            render: "bullpupshotgun.svg",
            name: "bullpupshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_bullpupshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MUKSET]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MUKSET,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "musket.svg",
            render: "musket.svg",
            name: "musket",
            description: "",
            count: 1,
            weight: 4.5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_musket",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HEAVYSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HEAVYSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavyshotgun.svg",
            render: "heavyshotgun.svg",
            name: "heavyshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_heavyshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_DBSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_DBSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "dbshotgun.svg",
            render: "dbshotgun.svg",
            name: "dbshotgun",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_AUTOSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_AUTOSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "autoshotgun.svg",
            render: "autoshotgun.svg",
            name: "autoshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_COMBATSHOTGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_COMBATSHOTGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatshotgun.svg",
            render: "combatshotgun.svg",
            name: "combatshotgun",
            description: "",
            count: 1,
            weight: 7,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sg_assaultshotgun",
            ammoType: "SHOTGUNAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultrifle.svg",
            render: "assaultrifle.svg",
            name: "assaultrifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_ASSAULTRIFLE_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "assaultriflemk2.svg",
            render: "assaultriflemk2.svg",
            name: "assaultriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "carbinerifle.svg",
            render: "carbinerifle.svg",
            name: "carbinerifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_CARBINERIFLE_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "carbineriflemk2.svg",
            render: "carbineriflemk2.svg",
            name: "carbineriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_carbinerifle",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_ADVANCEDRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_ADVANCEDRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "advancedrifle.svg",
            render: "advancedrifle.svg",
            name: "advancedrifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_advancedrifle",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "specialcarbine.svg",
            render: "specialcarbine.svg",
            name: "specialcarbine",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_specialcarbine",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SPECIALCARBINE_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "specialcarbinemk2.svg",
            render: "specialcarbinemk2.svg",
            name: "specialcarbinemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_specialcarbine",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpuprifle.svg",
            render: "bullpuprifle.svg",
            name: "bullpuprifle",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_bullpuprifle",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE_MK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BULLPUPRIFLE_MK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bullpupriflemk2.svg",
            render: "bullpupriflemk2.svg",
            name: "bullpupriflemk2",
            description: "",
            count: 1,
            weight: 4,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_bullpuprifle",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_COMPACTRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_COMPACTRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "compactrifle.svg",
            render: "compactrifle.svg",
            name: "compactrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MILITARYRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MILITARYRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "militaryrifle.svg",
            render: "militaryrifle.svg",
            name: "militaryrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HEAVYRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HEAVYRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavyrifle.svg",
            render: "heavyrifle.svg",
            name: "heavyrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_TACTICALRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_TACTICALRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "tacticalrifle.svg",
            render: "tacticalrifle.svg",
            name: "tacticalrifle",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_assaultrifle_smg",
            ammoType: "RIFLEAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "mg.svg",
            render: "mg.svg",
            name: "mg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_mg",
            ammoType: "LMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_COMBATMG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_COMBATMG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatmg.svg",
            render: "combatmg.svg",
            name: "combatmg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_combatmg",
            ammoType: "LMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_COMBATMGMK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_COMBATMGMK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "combatmgmk2.svg",
            render: "combatmgmk2.svg",
            name: "combatmgmk2",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_combatmg",
            ammoType: "LMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GUSENBERG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GUSENBERG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "gusenberg.svg",
            render: "gusenberg.svg",
            name: "gusenberg",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sb_gusenberg",
            ammoType: "LMGAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SNIPERRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SNIPERRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "sniperrifle.svg",
            render: "sniperrifle.svg",
            name: "sniperrifle",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_sniperrifle",
            ammoType: "SNIPERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPER,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavysniper.svg",
            render: "heavysniper.svg",
            name: "heavysniper",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_heavysniper",
            ammoType: "SNIPERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPERMK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HEAVYSNIPERMK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "heavysnipermk2.svg",
            render: "heavysnipermk2.svg",
            name: "heavysnipermk2",
            description: "",
            count: 1,
            weight: 15,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_heavysniper",
            ammoType: "SNIPERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanrifle.svg",
            render: "marksmanrifle.svg",
            name: "marksmanrifle",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLEMK2]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MARKSMANRIFLEMK2,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "marksmanriflemk2.svg",
            render: "marksmanriflemk2.svg",
            name: "marksmanriflemk2",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PRECISIONRIFLE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PRECISIONRIFLE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "precisionrifle.svg",
            render: "precisionrifle.svg",
            name: "precisionrifle",
            description: "",
            count: 1,
            weight: 8,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_sr_marksmanrifle",
            ammoType: "SNIPERAMMO"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_COMPACTLAUNCHER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_COMPACTLAUNCHER,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "compactlauncher.svg",
            render: "compactlauncher.svg",
            name: "compactlauncher",
            description: "",
            count: 1,
            weight: 3,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_FIREWORK]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_FIREWORK,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "firework.svg",
            render: "firework.svg",
            name: "firework",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_firework",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHERSMOKE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHERSMOKE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "granadelaunchersmoke.svg",
            render: "granadelaunchersmoke.svg",
            name: "granadelaunchersmoke",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GRENADELAUNCHER,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "grenadelauncher.svg",
            render: "grenadelauncher.svg",
            name: "grenadelauncher",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_grenadelauncher",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_HOMINGLAUNCHER]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_HOMINGLAUNCHER,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "hominglauncher.svg",
            render: "hominglauncher.svg",
            name: "hominglauncher",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_homing",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MINIGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MINIGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "minigun.svg",
            render: "minigun.svg",
            name: "minigun",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_mg_minigun",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_RAILGUN]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_RAILGUN,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "railgun.svg",
            render: "railgun.svg",
            name: "railgun",
            description: "",
            count: 1,
            weight: 6,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ar_railgun",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_RPG]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_RPG,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "rpg.svg",
            render: "rpg.svg",
            name: "rpg",
            description: "",
            count: 1,
            weight: 5,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_lr_rpg",
            ammoType: ""
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BALL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BALL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "ball.svg",
            render: "ball.svg",
            name: "ball",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_golf_ball"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_BZGAS]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_BZGAS,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "bzgas.svg",
            render: "bzgas.svg",
            name: "bzgas",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_gas_grenade"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SMOKEGRENADE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SMOKEGRENADE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "smokegrenade.svg",
            render: "smokegrenade.svg",
            name: "smokegrenade",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_gas_grenade"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_FLARE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_FLARE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "flare.svg",
            render: "flare.svg",
            name: "flare",
            description: "",
            count: 1,
            weight: 0.1,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_am_flare"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_GRENADE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_GRENADE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "grenade.svg",
            render: "grenade.svg",
            name: "grenade",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_grenadefrag"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_MOLOTOV]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_MOLOTOV,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "molotov.svg",
            render: "molotov.svg",
            name: "molotov",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_molotov"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PROXIMITYMINE]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PROXIMITYMINE,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "proximymine.svg",
            render: "proximymine.svg",
            name: "proximymine",
            description: "",
            count: 1,
            weight: 12,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_apmine"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_PIPEBOMB]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_PIPEBOMB,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "pipebomb.svg",
            render: "pipebomb.svg",
            name: "pipebomb",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_bomb_01_s"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_SNOWBALL]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_SNOWBALL,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "snowball.svg",
            render: "snowball.svg",
            name: "snowball",
            description: "",
            count: 1,
            weight: 0.2,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "w_ex_snowball"
        },
        [itemData.ITEM_TYPES.ITEM_TYPE_STICKYBOMB]: {
            type: itemData.ITEM_TYPES.ITEM_TYPE_STICKYBOMB,
            typeCategory: itemData.ITEM_TYPE_CATEGORY.TYPE_WEAPON,
            hash: "",
            key: "",
            quality: 0,
            image: "stickybomb.svg",
            render: "stickybomb.svg",
            name: "stickybomb",
            description: "",
            count: 1,
            weight: 10,
            maxStack: 1,
            options: ["drop", "trade", "fast"],

            gender: null,
            isPlaced: false,
            modelHash: "prop_bomb_01_s"
        }
    }
}

module.exports = { inventoryAssets, itemData }